### ISSUE TITLE
Cannot load the package - some width and height are claimed being negative.

### ISSUE THREAD

**Issue by vkotkas** [CoCoViLa/HVACmodel#1]

**Comment by dragazhar** [comment]
Example pls or screenshot

**Comment by vkotkas** [comment]
Ok, in the xml it is referred to path="\images\multiSeriesGraph.png". The file iself has name MultiSeriesGraph.png.

**Comment by dragazhar** [comment]
I suppose this depends on how the  the file names are handled (case sensitive or not)
